name: Update Pinecone Index

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-pinecone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          check-latest: true

      - name: Build and run upsert script
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        run: |
          cd scripts
          go run upsert_pinecone.go --path ../docs --namespace go-vibes 